navigator/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name="index"),
    path('products', include('products.urls', namespace='products'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products.views import products, search_products, product_detail


app_name = 'products'

urlpatterns = [
  path('', products, name='index'),
  path('category/<int:category_id>/', products, name='category'),
  path('educationFormat/<int:educationFormat_id>/', products, name='educationFormat'),
  path('transEducation/<int:transEducation_id>/', products, name='transEducation'),
  path('search/', search_products, name='search'),
  path('product/<int:pk>/', product_detail, name='product_detail'),
]

products/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from teacher.models import EducationTeacher

class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'Категории'
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name



class ProductFormat(models.Model):
    class Meta:
        verbose_name = 'Формат продукта'
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

class EducationTime(models.Model):
    class Meta:
        verbose_name = 'Продолжительность курса'
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

class EducationTrans(models.Model):
    class Meta:
        verbose_name = 'Сложность курса'
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

class EducationOneLesson(models.Model):
    class Meta:
        verbose_name = 'Продолжительность одного урока'
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
    name = models.CharField(max_length=256)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=20, decimal_places=0)
    image = models.ImageField(upload_to='products__images')
    category = models.ForeignKey(to=ProductCategory, on_delete=models.PROTECT)
    rating = models.PositiveIntegerField(default=0, blank=True, validators=[MinValueValidator(1), MaxValueValidator(5)])
    educationTime = models.ForeignKey(to=EducationTime, on_delete=models.PROTECT, blank=True)
    educationLocation = models.CharField(max_length=256, blank=True)
    educationFormat = models.ForeignKey(to=ProductFormat, on_delete=models.PROTECT)
    productUrl = models.TextField(blank=True)
    educationTeacher = models.ForeignKey(to=EducationTeacher, on_delete=models.PROTECT)
    timeLesson = models.ForeignKey(to=EducationOneLesson, on_delete=models.PROTECT, blank=True)
    transEducation = models.ForeignKey(to=EducationTrans, on_delete=models.PROTECT, blank=True)



    def __str__(self):
        return self.name

class ProgrammProduct(models.Model):
    class Meta:
        verbose_name = 'Программа продукта'
    name = models.CharField(max_length=256)
    program = models.TextField()
    product = models.ForeignKey(to=Product, on_delete=models.PROTECT)



    def __str__(self):
        return f'Продукт: {self.name} | Категория: {self.category.name}'

teacher/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class EducationTeacher(models.Model):
    class Meta:
        verbose_name = 'Учитель'
    name = models.CharField(max_length=128, unique=True)
    age = models.DecimalField(max_digits=2, decimal_places=0, validators=[MinValueValidator(1), MaxValueValidator(80)])
    ageEducation = models.DecimalField(max_digits=2, decimal_places=0, validators=[MinValueValidator(1), MaxValueValidator(40)])
    imageTeacher = models.ImageField(upload_to='avatar__image', blank=True)


    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import render
# Create your views here.

from products.models import ProductCategory, ProductFormat, EducationTrans, Product




def index(request):
    context = {
        'title': 'Navigator',
        'categories': ProductCategory.objects.all(),
        'educationFormats': ProductFormat.objects.all(),
        'transEducations': EducationTrans.objects.all(),
        'products': Product.objects.all(),
    }
    return render(request, 'products/index.html', context)

def products(
        request, 
        category_id=None, 
        educationFormat_id=None, 
        transEducation_id=None):
    if category_id:
        category = ProductCategory.objects.get(id=category_id)
        products = Product.objects.filter(category=category)
    if educationFormat_id:
        educationFormat = ProductFormat.objects.get(id=educationFormat_id)
        products = Product.objects.filter(educationFormat=educationFormat)
    if transEducation_id:
        transEducation = EducationTrans.objects.get(id=transEducation_id)
        products = Product.objects.filter(transEducation=transEducation)
    else:
        products = Product.objects.all()
    context = {
        'title': 'Navigator | Products',
        'categories': ProductCategory.objects.all(),
        'educationFormats': ProductFormat.objects.all(),
        'transEducations': EducationTrans.objects.all(),
        'products': products,
    }
    return render(request, 'products/products.html', context)

def search_products(request):
    query = request.GET.get('q')
    if query:
        products = Product.objects.filter(name__icontains=query)
    else:
        products = Product.objects.all()

    context = {
        'title': 'Navigator | Search Results',
        'categories': ProductCategory.objects.all(),
        'educationFormats': ProductFormat.objects.all(),
        'transEducations': EducationTrans.objects.all(),
        'products': products,
    }
    return render(request, 'products/search_results.html', context)

def product_detail(request, pk):
    product = Product.objects.get(pk=pk)
    return render(request, 'products/product_detail.html', {'product': product})

teacher/views.py
from django.shortcuts import render

# Create your views here.

products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<link rel="stylesheet" href="{% static 'vendor/css/index.css' %}" />
		<link rel="stylesheet" href="{% static 'vendor/css/header.css' %}" />
		<link rel="stylesheet" href="{% static 'vendor/css/footer.css' %}" />
		<!--Custom styles for this template-->
		{% block css %} {% endblock %}
		<title>{{ title }}</title>
	</head>
	<body>
		<header class="header">
			<div class="header__container">
				<div class="header__inner">
					<a href="/" class="header__logo"></a>
					<div class="header__nav">
						<div class="header-nav">
							<div class="nav__item">
								<a
									tabindex="0"
									class="button--header secondary--header l--header"
									href="{% url 'index' %}"
								>
									<span class="button__label">Главная</span>
								</a>
							</div>
							<div class="nav__item">
								<a
									tabindex="0"
									class="button--header secondary--header l--header"
									href="{% url 'products:index' %}"
								>
									<span class="button__label">Курсы</span>
								</a>
							</div>
							<div class="nav__item nav__item--login">
								<a
									tabindex="0"
									class="button--header primary--header log--header"
									href="/accounts/login/"
								>
									<span class="button__label">Войти</span>
								</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</header>
		<main id="main-content" class="main-content">
			{% block content %} {% endblock %}
		</main>
		<footer class="footer">
			<div class="footer__container">
				<div class="footer__inner">
					<div class="footer__links">
						<a href="" class="footer__link">Условия</a>
						<a href="" class="footer__link">Конфиденциальность</a>
						<a href="" class="footer__link">Способы оплаты</a>
						<a href="" class="footer__link">Контакты</a>
						<a href="" class="footer__link"
							>Сведения об образовательной организации</a
						>
					</div>
					<div class="footer__copyright">
						<span class="footer__copyright-text">Все права защищены</span>
					</div>
				</div>
			</div>
		</footer>
	</body>
</html>

products/templates/products/product_detail.html
{% extends 'products/base.html' %} {% load static %} {% block css %}
<link
	rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
/>

<link rel="stylesheet" href="{% static 'vendor/css/product_detail.css'%}" />

{% endblock %} {% block content %}
<div
	class="section_one"
	style="background: url(../../../media/{{product.image}});"
>
	<div class="base-container">
		<div class="main_container">
			<div class="title-list">
				<div class="option_list">
					<h1>{{ product.name }}</h1>
					<p>{{ product.description }}</p>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

<h1>{{ product.title }}</h1>
<p>{{ product.description }}</p>
<p>Price: ${{ product.price }}</p>

products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'vendor/css/products.css'%}">
{% endblock %}

{% block content %}
    <div class="base-container">
        <div class="course-list">
            <div class="header">
                <h1 class="title">Огромный выбор курсов</h1>
                <h6 class="subtitle">
                    Прокачай себя курсами разных направлений: рисование, программирование, робототехника и многое другое
                </h6>
            </div>
            <!--<div class="subheader">
                <div class="subheader__section subheader__section--start">
                    <mwc-textfield outlined="" class="search" label="Поиск по курсам" name="search" icon="search"></mwc-textfield>
                    <base-button size="l" iconbutton="" icon="filter" class="filters-button">filter</base-button>
                </div>
                <div class="subheader__section subheader__section--end">
                    <div class="modes">
                        <button class="mode mode--active">
                            <mwc-icon>list_view</mwc-icon>
                        </button>
                        <button class="mode">
                            <mwc-icon>grid_view</mwc-icon>
                        </button>
                    </div>
                <div>
                <course-list-ordering>
                    <button class="button">
                        <span class="button__text">
                         По популярности
                        </span>
                        <mwc-icon class="button__icon">sort_down</mwc-icon>
                    </button>
                </course-list-ordering>
              </div>
            </div>
          </div>-->

            <!--<div class="main">
                <div class="main-section main-section--start">
                    <div>
                        <div class="course-list-filters">
                            <div class="header-filter">
                            <h4 class="title-filter">Фильтр</h4>
                                <span class="counter-empty">
                                  Фильтр не настроен
                                </span>
                          </div>
                            <select class="category" outlined="" name="category" id="">
                                option
                            </select>
                            <details class="item">
                                <summary>
                                  Цена
                                  <mwc-icon>chevron_down</mwc-icon>
                                </summary>

                                    <div class="chip">
                                      <input class="chip__input" type="checkbox" name="price" id="price-0" value="0">
                                      <label class="chip__label" for="price-0">
                    Бесплатно (25)
                                      </label>
                                    </div>
                              </details>
                        </div>
                    </div>
                </div>
            </div>-->

            <div class="popular-courses__courses__list">
                    <div class="popular-courses__slider popular-courses__swiper swiper swiper-initialized swiper-horizontal swiper-pointer-events swiper-backface-hidden">
                        <div class="swiper-wrapper" style="transition-duration: 0ms; transform: translate3d(0px, 0px, 0px);">
                            {% for product in products %}
                                <div class="course-card">
                                    <a class="card tablet" href="">
                                        <div class="card-header">
                                            <div class="rating">
                                                <div class="rating__star">
                                                    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                                        <g id="SVGRepo_iconCarrier">
                                                            <path d="M9.15316 5.40838C10.4198 3.13613 11.0531 2 12 2C12.9469 2 13.5802 3.13612 14.8468 5.40837L15.1745 5.99623C15.5345 6.64193 15.7144 6.96479 15.9951 7.17781C16.2757 7.39083 16.6251 7.4699 17.3241 7.62805L17.9605 7.77203C20.4201 8.32856 21.65 8.60682 21.9426 9.54773C22.2352 10.4886 21.3968 11.4691 19.7199 13.4299L19.2861 13.9372C18.8096 14.4944 18.5713 14.773 18.4641 15.1177C18.357 15.4624 18.393 15.8341 18.465 16.5776L18.5306 17.2544C18.7841 19.8706 18.9109 21.1787 18.1449 21.7602C17.3788 22.3417 16.2273 21.8115 13.9243 20.7512L13.3285 20.4768C12.6741 20.1755 12.3469 20.0248 12 20.0248C11.6531 20.0248 11.3259 20.1755 10.6715 20.4768L10.0757 20.7512C7.77268 21.8115 6.62118 22.3417 5.85515 21.7602C5.08912 21.1787 5.21588 19.8706 5.4694 17.2544L5.53498 16.5776C5.60703 15.8341 5.64305 15.4624 5.53586 15.1177C5.42868 14.773 5.19043 14.4944 4.71392 13.9372L4.2801 13.4299C2.60325 11.4691 1.76482 10.4886 2.05742 9.54773C2.35002 8.60682 3.57986 8.32856 6.03954 7.77203L6.67589 7.62805C7.37485 7.4699 7.72433 7.39083 8.00494 7.17781C8.28555 6.96479 8.46553 6.64194 8.82547 5.99623L9.15316 5.40838Z" fill="#4378FEFF">
                                                            </path>
                                                        </g>
                                                    </svg>
                                                </div>
                                                {{ product.rating }}
                                            </div>
                                        </div>
                                        <h3 class="title-course">{{ product.name }}</h3>
                                        <div class="chips">
                                            <div class="chips_item chips_item--online">{{ product.educationFormat }}</div>
                                            <div class="chips_item">{{ product.transEducation }}</div>
                                            <div class="chips_item">{{ product.category }}</div>
                                        </div>
                                        <div class="params">
                                            <div class="price">
                                                <div class="price__icon">
                                                    <svg fill="#4378FEFF" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" stroke="#4378FEFF">
                                                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                                                        <g id="SVGRepo_iconCarrier">
                                                            <path d="M19.388.405a.605.605 0 0 0-1.141.399c.929 2.67-.915 4.664-2.321 5.732l-.568-.814c-.191-.273-.618-.5-.95-.504l-3.188.014a2.162 2.162 0 0 0-1.097.338L.729 12.157a1.01 1.01 0 0 0-.247 1.404l4.269 6.108c.32.455.831.4 1.287.082l9.394-6.588c.27-.191.582-.603.692-.918l.998-3.145c.11-.314.043-.793-.148-1.066l-.346-.496c1.888-1.447 3.848-4.004 2.76-7.133zm-4.371 9.358a1.608 1.608 0 0 1-2.24-.396 1.614 1.614 0 0 1 .395-2.246 1.607 1.607 0 0 1 1.868.017c-.272.164-.459.26-.494.275a.606.606 0 0 0 .259 1.153c.086 0 .174-.02.257-.059.194-.092.402-.201.619-.33a1.615 1.615 0 0 1-.664 1.586z">
                                                            </path>
                                                        </g>
                                                    </svg>
                                                </div>
                                                {{ product.price }} ₽
                                            </div>
                                            <div class="lesson-duration">
                                                <div class="lesson-duration__icon">
                                                    <svg width="64px" height="64px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                                                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" stroke="#CCCCCC" stroke-width="0.624"></g>
                                                        <g id="SVGRepo_iconCarrier">
                                                            <path d="M12 7V12L10.5 14.5M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z" stroke="#595959" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                                            </path>
                                                        </g>
                                                    </svg>
                                                </div>
                                                {{ product.timeLesson }}
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
        </div>
    </div>
{% endblock %}

products/templates/products/search_results.html
{% extends 'products/base.html' %} {% load static %} {% block css %}
<link rel="stylesheet" href="{% static 'vendor/css/products.css'%}" />
<script src="{% static 'js/modules/base/material.js'%}"></script>
{% endblock %} {% block content %}
<div class="base-container">
	<div class="course-list">
		<div class="header">
			<h1 class="title">Огромный выбор курсов</h1>
			<h6 class="subtitle">
				Прокачай себя курсами разных направлений: рисование, программирование,
				робототехника и многое другое
			</h6>
		</div>
		<div class="filters">
			{% for category in categories %}
			<a href="{% url 'products:category' category.id %}"
				>{{ category.name }}</a
			>
			{% endfor %}
		</div>
		<div class="subheader">
			<div class="subheader__section subheader__section--start">
				<form method="GET" action="{% url 'products:search' %}">
					<input type="text" name="q" placeholder="Поиск по названию..." />
					<button type="submit">Искать</button>
				</form>
			</div>
			<div class="subheader__section subheader__section--end"></div>
		</div>
		<div class="popular-courses__courses__list">
			<div
				class="popular-courses__slider popular-courses__swiper swiper swiper-initialized swiper-horizontal swiper-pointer-events swiper-backface-hidden"
			>
				<div
					class="swiper-wrapper"
					style="
						transition-duration: 0ms;
						transform: translate3d(0px, 0px, 0px);
					"
				>
					{% for product in products %}
					<div class="course-card">
						<a class="card tablet" href="">
							<div class="card-header">
								<div class="rating">
									<div class="rating__star">
										<svg
											viewBox="0 0 24 24"
											fill="none"
											xmlns="http://www.w3.org/2000/svg"
										>
											<g id="SVGRepo_bgCarrier" stroke-width="0"></g>
											<g
												id="SVGRepo_tracerCarrier"
												stroke-linecap="round"
												stroke-linejoin="round"
											></g>
											<g id="SVGRepo_iconCarrier">
												<path
													d="M9.15316 5.40838C10.4198 3.13613 11.0531 2 12 2C12.9469 2 13.5802 3.13612 14.8468 5.40837L15.1745 5.99623C15.5345 6.64193 15.7144 6.96479 15.9951 7.17781C16.2757 7.39083 16.6251 7.4699 17.3241 7.62805L17.9605 7.77203C20.4201 8.32856 21.65 8.60682 21.9426 9.54773C22.2352 10.4886 21.3968 11.4691 19.7199 13.4299L19.2861 13.9372C18.8096 14.4944 18.5713 14.773 18.4641 15.1177C18.357 15.4624 18.393 15.8341 18.465 16.5776L18.5306 17.2544C18.7841 19.8706 18.9109 21.1787 18.1449 21.7602C17.3788 22.3417 16.2273 21.8115 13.9243 20.7512L13.3285 20.4768C12.6741 20.1755 12.3469 20.0248 12 20.0248C11.6531 20.0248 11.3259 20.1755 10.6715 20.4768L10.0757 20.7512C7.77268 21.8115 6.62118 22.3417 5.85515 21.7602C5.08912 21.1787 5.21588 19.8706 5.4694 17.2544L5.53498 16.5776C5.60703 15.8341 5.64305 15.4624 5.53586 15.1177C5.42868 14.773 5.19043 14.4944 4.71392 13.9372L4.2801 13.4299C2.60325 11.4691 1.76482 10.4886 2.05742 9.54773C2.35002 8.60682 3.57986 8.32856 6.03954 7.77203L6.67589 7.62805C7.37485 7.4699 7.72433 7.39083 8.00494 7.17781C8.28555 6.96479 8.46553 6.64194 8.82547 5.99623L9.15316 5.40838Z"
													fill="#4378FEFF"
												></path>
											</g>
										</svg>
									</div>
									{{ product.rating }}
								</div>
							</div>
							<h3 class="title-course">{{ product.name }}</h3>
							<div class="chips">
								<div class="chips_item chips_item--online">
									{{ product.educationFormat }}
								</div>
								<div class="chips_item">{{ product.transEducation }}</div>
								<div class="chips_item">{{ product.category }}</div>
							</div>
							<div class="params">
								<div class="price">
									<div class="price__icon">
										<svg
											fill="#4378FEFF"
											viewBox="0 0 20 20"
											xmlns="http://www.w3.org/2000/svg"
											stroke="#4378FEFF"
										>
											<g id="SVGRepo_bgCarrier" stroke-width="0"></g>
											<g
												id="SVGRepo_tracerCarrier"
												stroke-linecap="round"
												stroke-linejoin="round"
											></g>
											<g id="SVGRepo_iconCarrier">
												<path
													d="M19.388.405a.605.605 0 0 0-1.141.399c.929 2.67-.915 4.664-2.321 5.732l-.568-.814c-.191-.273-.618-.5-.95-.504l-3.188.014a2.162 2.162 0 0 0-1.097.338L.729 12.157a1.01 1.01 0 0 0-.247 1.404l4.269 6.108c.32.455.831.4 1.287.082l9.394-6.588c.27-.191.582-.603.692-.918l.998-3.145c.11-.314.043-.793-.148-1.066l-.346-.496c1.888-1.447 3.848-4.004 2.76-7.133zm-4.371 9.358a1.608 1.608 0 0 1-2.24-.396 1.614 1.614 0 0 1 .395-2.246 1.607 1.607 0 0 1 1.868.017c-.272.164-.459.26-.494.275a.606.606 0 0 0 .259 1.153c.086 0 .174-.02.257-.059.194-.092.402-.201.619-.33a1.615 1.615 0 0 1-.664 1.586z"
												></path>
											</g>
										</svg>
									</div>
									{{ product.price }} ₽
								</div>
								<div class="lesson-duration">
									<div class="lesson-duration__icon">
										<svg
											width="64px"
											height="64px"
											viewBox="0 0 24 24"
											fill="none"
											xmlns="http://www.w3.org/2000/svg"
										>
											<g id="SVGRepo_bgCarrier" stroke-width="0"></g>
											<g
												id="SVGRepo_tracerCarrier"
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke="#CCCCCC"
												stroke-width="0.624"
											></g>
											<g id="SVGRepo_iconCarrier">
												<path
													d="M12 7V12L10.5 14.5M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12Z"
													stroke="#595959"
													stroke-width="2"
													stroke-linecap="round"
													stroke-linejoin="round"
												></path>
											</g>
										</svg>
									</div>
									{{ product.timeLesson }}
								</div>
							</div>
						</a>
					</div>
					{% empty %}
					<li>Нет результатов</li>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}